project/accounts/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', RedirectView.as_view(pattern_name='accounts:login', permanent=False)),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup-prelim/', views.signup_prelim, name='signup-prelim'),
    path('signup-prelim-success/', views.signup_prelim_success, name='signup-prelim-success'),
    path('finish-setup/<str:signed_email>/', views.signup_finish_setup, name='signup-finish-setup'),
    path('password-reset-request/', views.password_reset_prelim, name='password-reset-prelim'),
    path('password-reset-requested/', views.password_reset_prelim_success, name='password-reset-prelim-success'),
    path('password-reset/<str:signed_email>/', views.password_reset, name='password-reset'),
]

project/launchpad/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'launchpad'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='launchpad:home', permanent=False)),
    path('home/', views.home.home, name='home'),
    path('terms/', views.terms.terms, name='terms'),
    path('eligibility/', views.eligibility.eligibility, name='eligibility'),
    path('buy/', views.buy.buy, name='buy'),
    path('payment/<slug:order_id>/', views.payment.payment, name='payment'),
    path('orders/', views.orders.orders, name='orders'),
    path('transactions/', views.transactions.transactions, name='transactions'),
    path('verification/', views.verification.verification, name='verification'),
    path('withdraw/', views.withdraw.withdraw, name='withdraw'),
    path('data/payment/update/', views.data.payment.update, name='data-payment-update'),
    path('stats/', views.stats.stats, name='stats'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/', permanent=False)),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^launchpad/', include('launchpad.urls')),
    # url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

project/launchpad/models.py
from django.db import models

from accounts.models import User
from launchpad.querysets.terms_policy_repo import TermsPolicyRepoQuerySet
from launchpad.querysets.token_orders import TokenOrdersQuerySet
from launchpad.querysets.token_transactions import TokenTransactionsQuerySet
from launchpad.querysets.user_eligibility_registry import UserEligibilityRegistryQuerySet
from launchpad.querysets.user_terms_registry import UserTermsRegistryQuerySet


class TermsPolicyRepo(models.Model):
    term_id = models.BigAutoField(primary_key=True)
    term_type = models.CharField(max_length=50, null=False)
    term_version = models.CharField(max_length=15, null=False)
    term_html = models.TextField(null=False)
    term_text = models.TextField(null=False)
    term_status = models.CharField(max_length=255, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,
                                      null=True)

    # Configuration
    #
    objects = TermsPolicyRepoQuerySet.as_manager()

    def __str__(self):
        return '%s - %s - %s' % (self.term_type, self.term_version, self.created_at)


class UserTermsRegistry(models.Model):
    user_term_id = models.BigAutoField(primary_key=True)
    customer_external_id = models.CharField(max_length=64, null=False)
    term = models.ForeignKey(TermsPolicyRepo,
                             db_column='term_id',
                             on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,
                                      null=True)

    # Configuration
    #
    objects = UserTermsRegistryQuerySet.as_manager()


class UserEligibilityRegistry(models.Model):
    user_eligibility_id = models.BigAutoField(primary_key=True)
    customer_external_id = models.CharField(max_length=64, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,
                                      null=True)

    # Configuration
    #
    objects = UserEligibilityRegistryQuerySet.as_manager()


class TokenOrders(models.Model):
    token_order_id = models.BigAutoField(primary_key=True)
    token_order_external_id = models.CharField(max_length=64, null=False)
    customer_external_id = models.CharField(max_length=64, null=False)
    usd_value = models.DecimalField(max_digits=12, decimal_places=2, null=False)
    token_value = models.DecimalField(max_digits=28, decimal_places=18, null=False)
    payment_currency = models.CharField(max_length=10, null=False)
    payment_currency_value = models.DecimalField(max_digits=28, decimal_places=18, null=True)
    payment_address = models.CharField(max_length=255, null=True)
    payment_destination_tag = models.CharField(max_length=25, null=True)
    txn_id = models.CharField(max_length=255, null=True)
    confirms_needed = models.IntegerField(null=True)
    timeout = models.IntegerField(null=True)
    status_url = models.CharField(max_length=255, null=True)
    qrcode_url = models.CharField(max_length=255, null=True)
    payment_status = models.IntegerField(null=True)
    payment_status_text = models.CharField(max_length=255, null=True)
    payment_received = models.BooleanField(null=False, default=False)
    tokens_credited = models.BooleanField(null=False, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,
                                      null=True)

    # Configuration
    #
    objects = TokenOrdersQuerySet.as_manager()

    class Meta:
        ordering = ['-token_order_id']


class TokenTransactions(models.Model):
    token_transaction_id = models.BigAutoField(primary_key=True)
    token_transaction_external_id = models.CharField(max_length=64, null=False)
    customer_external_id = models.CharField(max_length=64, null=False)
    transaction_type = models.CharField(max_length=25, null=False)
    token_value = models.DecimalField(max_digits=28, decimal_places=18, null=False)
    withdrawal_address = models.CharField(max_length=255, null=True)
    txn_id = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True,
                                      null=True)

    # Configuration
    #
    objects = TokenTransactionsQuerySet.as_manager()

    class Meta:
        ordering = ['-token_transaction_id']

project/launchpad/forms/eligibility_forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, ButtonHolder, HTML, Field
from django import forms


class EligibilityConfirmationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(EligibilityConfirmationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-eligibilityConfirmationForm'
        self.helper.form_method = 'post'
        self.helper.render_hidden_fields = True
        self.helper.include_media = False
        self.helper.layout = Layout(
            ButtonHolder(
                Submit('submit', 'Continue', css_id='eligibility-check-submit'),
            ),
        )

project/launchpad/views/buy.py
import random
from secrets import token_urlsafe

from anymail.message import AnymailMessage
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from launchpad.forms.buy_forms import BuyForm
from launchpad.models import UserEligibilityRegistry, TokenOrders
from launchpad.services.pyCoinPayments import CryptoPayments
from project.settings import env


@login_required
def buy(request):
    _user_id_external = request.user.id_external
    _user_email = request.user.email
    _user_eligibility_latest = UserEligibilityRegistry.objects.last_consent(external_id=_user_id_external)
    _token_cost_usd = 0.1

    if len(_user_eligibility_latest) == 0:
        return redirect('launchpad:eligibility')

    if request.method == 'POST':
        _buy_form = BuyForm(request.POST)

        if _buy_form.is_valid():
            _usd_value = _buy_form.cleaned_data.get('usd_value')
            _payment_currency = _buy_form.cleaned_data.get('payment_currency')

            _token_value = int(_usd_value) / _token_cost_usd
            _token_order_external_id = token_urlsafe(32)

            _cp_client = CryptoPayments(
                env('COINPAYMENTS_API_KEY'),
                env('COINPAYMENTS_API_SECRET'),
                env('COINPAYMENTS_IPN_URL'),
            )

            _token_order = TokenOrders(
                token_order_external_id=_token_order_external_id,
                customer_external_id=_user_id_external,
                usd_value=_usd_value,
                token_value=_token_value,
                payment_currency=_payment_currency,
            )

            _token_order.save()
            _token_order_id = _token_order.token_order_id

            _item_name = 'Centive Tokens (XTV)'
            _item_number = str(random.randint(10, 100)) + str(_token_order_id) + str(random.randint(10, 100))

            _cp_transaction = _cp_client.createTransaction({
                'amount': _usd_value,
                'currency1': 'USD',
                'currency2': _payment_currency,
                'buyer_email': _user_email,
                'item_name': _item_name,
                'item_number': _item_number,
            })

            _token_order.payment_currency_value = _cp_transaction.amount
            _token_order.payment_address = _cp_transaction.address
            _token_order.txn_id = _cp_transaction.txn_id
            _token_order.confirms_needed = _cp_transaction.confirms_needed
            _token_order.timeout = _cp_transaction.timeout
            _token_order.status_url = _cp_transaction.status_url
            _token_order.qrcode_url = _cp_transaction.qrcode_url

            _token_order.save()

            _message = AnymailMessage(
                to=[_user_email],
                tags=['Orders']
            )
            _message.template_id = '9125877d-e602-4375-8ad2-74dbad9ec04d'
            _message.merge_global_data = {
                'token_value': ' '.join([str("{:,.2f}".format(float(_token_value))), 'XTV']),
                'confirms_needed': _cp_transaction.confirms_needed,
                'payment_currency_value': ' '.join([str(_cp_transaction.amount), _payment_currency]),
                'payment_address': _cp_transaction.address,
                'status_url': _cp_transaction.status_url,
            }
            _message.metadata = {'payment-address': _cp_transaction.address}
            _message.track_clicks = True

            _message.send()

            return redirect('launchpad:payment', order_id=_token_order_external_id)

        else:
            return render(request, 'launchpad/buy.html', {'buy_form': _buy_form})

    else:
        _buy_form = BuyForm()
        return render(request, 'launchpad/buy.html', {'buy_form': _buy_form})

project/launchpad/views/eligibility.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe

from launchpad.forms.eligibility_forms import EligibilityConfirmationForm
from launchpad.models import UserEligibilityRegistry


@login_required
def eligibility(request):
    _user_id_external = request.user.id_external
    _user_eligibility_latest = UserEligibilityRegistry.objects.last_consent(external_id=_user_id_external)

    if len(_user_eligibility_latest) == 0:
        if request.method == 'POST':
            _eligibility_form = EligibilityConfirmationForm(request.POST)

            if _eligibility_form.is_valid():
                _user_eligibility = UserEligibilityRegistry(customer_external_id=_user_id_external)
                _user_eligibility.save()

                return redirect('launchpad:buy')
            else:
                _eligibility_form.add_error(None, mark_safe('Oops! Something went wrong. Please try again later.'))

                return render(request, 'launchpad/eligibility.html', {
                    'eligibility_form': _eligibility_form,
                })
        else:
            _eligibility_form = EligibilityConfirmationForm()

            return render(request, 'launchpad/eligibility.html', {
                'eligibility_form': _eligibility_form,
            })
    else:
        return redirect('launchpad:buy')

project/launchpad/views/home.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.models import UserProfile
from launchpad.models import TermsPolicyRepo, UserTermsRegistry, TokenOrders, TokenTransactions


@login_required
def home(request):
    _user_id_external = request.user.id_external
    _user_profile = UserProfile.objects.basic_profile(user_id=request.user.id).get()

    _terms_repo_latest = TermsPolicyRepo.objects.latest_term(term_type='terms-conditions')
    _user_term_latest = UserTermsRegistry.objects.last_consent(external_id=_user_id_external,
                                                               term_type='terms-conditions')

    if len(_user_term_latest) == 0 or _user_term_latest[0].term.term_id != _terms_repo_latest[0].term_id:
        return redirect('launchpad:terms')

    else:
        _pending_orders = TokenOrders.objects.token_orders(customer_external_id=_user_id_external).pending()
        _token_holdings = TokenTransactions.objects.token_transactions(
            customer_external_id=_user_id_external
        ).holdings()

        return render(request, 'launchpad/home.html', {
            'user_profile': _user_profile,
            'pending_orders': _pending_orders,
            'token_holdings': _token_holdings,
        })

project/launchpad/views/orders.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from launchpad.models import TokenOrders


@login_required
def orders(request):
    _user_id_external = request.user.id_external

    _orders = TokenOrders.objects.token_orders(customer_external_id=_user_id_external)
    return render(request, 'launchpad/orders.html', {'orders': _orders})

project/launchpad/views/payment.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from launchpad.models import TokenOrders


@login_required
def payment(request, order_id):
    _user_id_external = request.user.id_external

    _token_order = TokenOrders.objects.token_orders(
        customer_external_id=_user_id_external,
        token_order_external_id=order_id,
    )

    if len(_token_order) > 0:
        return render(request, 'launchpad/payment.html', {'token_order': _token_order[0]})
    else:
        return redirect('launchpad:home')

project/launchpad/views/stats.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from launchpad.models import TokenOrders, TokenTransactions


@login_required
def stats(request):
    if request.user.is_staff:
        _orders = TokenOrders.objects
        _sales = TokenTransactions.objects
        _users = get_user_model().objects

        return render(request, 'launchpad/stats.html', {
            'orders': {
                'total': _orders.count(),
                'completed': _orders.completed().count(),
                'pending': _orders.pending().count(),
                'cancelled': _orders.cancelled().count(),
                'stats': _orders.completed().stats(),
            },
            'sales': _sales.deposits().holdings(),
            'users': {
                'total': _users.active_users().count(),
            }
        })
    else:
        return redirect('launchpad:home')

project/launchpad/views/transactions.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from launchpad.models import TokenTransactions


@login_required
def transactions(request):
    _user_id_external = request.user.id_external

    _transactions = TokenTransactions.objects.token_transactions(customer_external_id=_user_id_external)
    return render(request, 'launchpad/transactions.html', {'transactions': _transactions})

project/launchpad/views/verification.py
import requests
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from requests import RequestException

from project.settings import env


@login_required
def verification(request):
    _user_id_external = request.user.id_external

    _sumsub_access_token_payload = {
        'userId': _user_id_external,
        'key': env('SUMSUB_KEY'),
    }

    try:
        _sumsub_request = requests.post(
            '/'.join([env('SUMSUB_HOST'), 'resources/accessTokens']),
            params=_sumsub_access_token_payload
        )

        _sumsub_request.raise_for_status()

        _sumsub_response = _sumsub_request.json()

        return render(request, 'launchpad/verification.html', {
            'sumsub': {
                'host': env('SUMSUB_HOST'),
                'token': _sumsub_response['token'],
            }
        })

    except RequestException:
        return render(request, 'launchpad/verification_unavailable.html')

project/launchpad/templates/launchpad/body_base.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx" class="js">
<head>
    {% block meta-tags %}
        <meta charset="utf-8">
        <meta name="author" content="Centive">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Centive is a blockchain-based incentive network centered on frictionless and ultra-low cost transactions with tokens. We focus on platform development, adoption and user growth to generate value for all users.">
    {% endblock meta-tags %}

    <link rel="shortcut icon" href="{% static 'launchpad/img/brand/cropped-favicon-centive-1-32x32.png' %}">
    <title>{% block title %}Centive{% endblock title %}</title>

    {% block css-loads %}
        <!-- Vendor Bundle CSS -->
        <link rel="stylesheet" href="{% static 'launchpad/css/bootstrap.min.css' %}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="{% static 'launchpad/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'launchpad/css/theme.css' %}">
        <link href="{% static 'launchpad/css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

        <link href="{% static 'launchpad/css/custom.css' %}" rel="stylesheet">
    {% endblock css-loads %}
</head>

<body id="{% block body-id %}{% endblock body-id %}" class="theme-light io-light-pro theme-lavendar io-lavendar {% block body-class %}{% endblock body-class %}" data-spy="scroll" data-target="#mainnav" data-offset="80">

    {% block body-content %}{% endblock body-content %}

    {% block js-loads %}
        <script src="{% static 'launchpad/js/jquery.bundle.js' %}"></script>
        <script src="{% static 'launchpad/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'launchpad/js/script.js' %}"></script>
        <script src="{% static 'launchpad/js/plugins/toastr/toastr.min.js' %}"></script>
        <script src="{% static 'launchpad/js/custom.js' %}"></script>

        {% if messages %}
            <script>
                {% for message in messages %}
                    toastr['{{ message.tags }}']('{{ message }}');
                {% endfor %}
            </script>
        {% endif %}
    {% endblock js-loads %}
</body>
</html>

project/launchpad/templates/launchpad/home.html
{% extends 'launchpad/body_base.html' %}
{% block title %}Manage Your Tokens - {{ block.super }}{% endblock title %}

{% load static %}
{% load gravatar %}
{% load humanize %}

{% block body-content %}
    <div class="user-page d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                        {% include 'launchpad/nav_bar.html' with page_cat='home' %}
                        <div class="row">
                            <div class="col-lg-12" style="background-image: url('{% static 'launchpad/img/patterns/subtle-crisscross.jpg' %}');">
                                <div class="p-2">
                                    {% if pending_orders %}
                                        <div class="alert alert-warning border text-center">
                                            You have <a href="{% url 'launchpad:orders' %}"><b>{{ pending_orders|length }} pending order{{ pending_orders|length|pluralize:',s' }}</b></a>
                                        </div>
                                    {% endif %}
                                    <div class="row mt-3">
                                        <div class="col-lg-6">
                                            <div class="position-relative col-centered middle-box-flex">
                                                <div class="balance-circle bg-white shadow-sm"></div>
                                                <div class="position-absolute" style="width:100%;">
                                                    <h5 class="text-center font-weight-light">Your balance</h5>
                                                    <h1 class="font-weight-bold text-center">
                                                        {% if token_holdings.tokens %}
                                                            {{ token_holdings.tokens.normalize|intcomma }}
                                                        {% else %}
                                                            0
                                                        {% endif %}
                                                    </h1>
                                                    <h4 class="font-weight-bold text-center">XTV</h4>
                                                    <div class="text-center"><a href="{% url 'launchpad:buy' %}"><button class="btn btn-alt btn-lg btn-encourage">Buy Tokens</button></a></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-5 rounded bg-white shadow-sm mt-x2 mt-sm-3 mt-md-3 mt-lg-0 ml-lg-5 ml-sm-0 pb-3 pt-3">
                                            <h4 class="al-center-sm">Your Withdrawal Address</h4>
                                            <h6 class="bg-light rounded border p-2 text-monospace mb-0" style="cursor:default;">
                                                {% if user_profile.withdrawal_address %}
                                                    {{ user_profile.withdrawal_address }}
                                                {% else %}
                                                    You have not set a withdrawal address yet.
                                                {% endif %}
                                            </h6>
                                            <div class="al-center-sm mt-0"><span class="text-muted">&#9654;</span> <a href="{% url 'launchpad:withdraw' %}">Change address</a></div>
                                            <hr class="hr mt-4 mb-4" />
                                            <h4 class="al-center-sm">Token Details</h4>
                                            <h6 class="font-weight-bold m-0">Type</h6>
                                            <h6 class="m-0 text-monospace">Ethereum (ERC20)</h6>
                                            <h6 class="font-weight-bold m-0 mt-3">Contract Address (Click for Etherscan token page)</h6>
                                            <h6 class="m-0 text-monospace"><a href="https://etherscan.io/token/0xda9da458c3dbec5797ef5b07a6b3199cbc045b18" target="_blank">0xda9da458c3dbec5797ef5b07a6b3199cbc045b18</a></h6>
                                            <h6 class="font-weight-bold m-0 mt-3">Symbol</h6>
                                            <h6 class="m-0 text-monospace">XTV</h6>
                                            <h6 class="font-weight-bold m-0 mt-3">Decimals</h6>
                                            <h6 class="m-0 text-monospace">18 digits</h6>
                                            <h6 class="font-weight-bold m-0 mt-3">Token Price</h6>
                                            <h6 class="m-0 text-monospace">$0.10 per XTV</h6>
                                            <h6 class="font-weight-bold m-0 mt-3">Token Home</h6>
                                            <h6 class="m-0 text-monospace"><a href="https://centive.org" target="_blank">centive.org</a></h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body-content %}

project/launchpad/templates/launchpad/nav_bar.html
{% load static %}
{% load gravatar %}
<div class="row">
    <div class="col-md-2">
        <a href="{% url 'launchpad:home' %}"><img src="{% static 'launchpad/img/brand/logo-centive-color.png' %}" border="0"></a>
    </div>
    <div class="col-md-10 text-right">
        <div class="d-inline-block mr-1">
            <div class="font-weight-bold">{{ user.email }}</div>
            <div class="font-weight-bold"><a href="{% url 'accounts:password-reset-prelim' %}">Change password</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{% url 'accounts:logout' %}">Logout</a></div>
        </div>
        <div class="d-inline">
            <img src="{% gravatar_url user.email 55 %}">
        </div>
    </div>
</div>
<div class="user-pro-box mt-2 shadow-sm border">
    {% if not show_nav or show_nav == 'True' %}
        <div class="topnav" id="top-nav">
            <a href="{% url 'launchpad:home' %}" {% if page_cat == 'home' %}class="active"{% endif %}>Home</a>
            <a href="{% url 'launchpad:orders' %}" {% if page_cat == 'orders' %}class="active"{% endif %}>Orders</a>
            <a href="{% url 'launchpad:transactions' %}" {% if page_cat == 'transactions' %}class="active"{% endif %}>Transactions</a>
            <a href="{% url 'launchpad:verification' %}" {% if page_cat == 'verification' %}class="active"{% endif %}>Verification</a>
            <a href="{% url 'launchpad:withdraw' %}" {% if page_cat == 'withdraw' %}class="active"{% endif %}>Withdraw</a>
            {% if user.is_staff %}
                <a href="{% url 'launchpad:stats' %}" {% if page_cat == 'stats' %}class="active"{% endif %}>Crowdsale Stats</a>
            {% endif %}
            <a href="javascript:void(0);" class="icon" onclick="dynamicTopNav()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
    {% endif %}

project/launchpad/templates/launchpad/withdraw.html
{% extends 'launchpad/body_base.html' %}
{% block title %}Buy XTV - {{ block.super }}{% endblock title %}

{% load static %}
{% load crispy_forms_tags %}
{% load gravatar %}

{% block js-loads %}
    {{ block.super }}
    <script src="{% static 'launchpad/js/plugins/jsSHA/sha3.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>
    <script>
        jQuery(document).ready(function($) {
            var web3 = new Web3();

            var displayAddressHelper = function (address){
                if(web3.isAddress(address)){
                    $('#address-helper-correct').show();
                    $('#address-helper-wrong').hide();
                } else {
                    $('#address-helper-correct').hide();
                    $('#address-helper-wrong').show();
                }
            };

            displayAddressHelper($('#id_withdrawal_address').val());

            $('#id_withdrawal_address').on('input propertychange paste', function (){
                var address = $(this).val();
                displayAddressHelper(address);
            });
        });
    </script>
{% endblock js-loads %}

{% block body-content %}
    <div class="user-page d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                        {% include 'launchpad/nav_bar.html' with page_cat='withdraw' %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="p-lg-5 p-md-3 p-sm-3 p-3">
                                    <div>
                                        <div class="rounded p-3 shadow-sm bg-light-alternet">
                                            <h5 class="font-weight-bold">Important Information</h5>
                                            <p>
                                                You will be able to withdraw your tokens once the ICO crowdsale comes to an end.<br />
                                                As of now, the crowdsale comes to an end on <b>31st October 2018.</b><br />
                                                Meanwhile, please complete the <a href="{% url 'launchpad:verification' %}">verification process (KYC)</a> and keep your withdrawal address updated.
                                            </p>
                                            <hr class="hr mt-1 mb-2" />
                                            <p class="text-danger">
                                                Do not use an exchange address (like Binance or Bitfinex). Any tokens sent to an exchange address will be lost forever.<br />
                                                Instead, you can use <a href="https://www.myetherwallet.com/" target="_blank">MyEtherWallet</a> or your own <a href="https://www.ethereum.org/" target="_blank">downloaded Ethereum wallet</a>.
                                            </p>
                                        </div>
                                        <div class="row mt-4">
                                            <div class="col-lg-6 al-center-sm">
                                                {% if update_success %}
                                                    <div class="alert alert-success">Successfully updated withdrawal address.</div>
                                                {% endif %}
                                                {% crispy address_update_form %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body-content %}